### ISSUE TITLE
Wrong language pair names in the README

### ISSUE THREAD

**Issue by AMR-KELEG** [apertium/apertium-mlt-ara#2]
I was trying to use the language pair locally on my computer.
After running `make` I used the command mentioned in the Testing part of the README `$  echo "Ilbieraħ kien kiesaħ ħafna." | apertium -d . mt-ar`.
Here the output errors:
```
echo "Ilbieraħ kien kiesaħ ħafna." | apertium -d . mt-ar
Error: Mode mt-ar does not exist. Try one of:
  ara-mlt-biltrans
  ara-mlt-debug
  ara-mlt
  ara-mlt-morph
  ara-mlt-tagger
  ara-mlt-transfer
  ara-mlt_translit
  mlt-ara-bidix
  mlt-ara-cg
  mlt-ara-dgen
  mlt-ara-interchunk
  mlt-ara
  mlt-ara-morph
  mlt-ara-postchunk
  mlt-ara-tagger
  mlt-ara-transfer
```
So, apparently the language pair has been renamed to `mlt-ara`.

I also believe that the `Files and data` section needs to be updated.

**Comment by jonorthwash** [comment]
Thanks for pointing this out and filing a PR to fix it!

**Comment by AMR-KELEG** [comment]
@jonorthwash I wanted to update the list of files `Files and data` but I will need to understand the files' extensions first so that I can write a short description for each one.
I believe we should re-open the issue till I fix the `Files and data` section.

I also want to update the file such that it's written in Markdown.
Do you think using Markdown will be better?
